### ISSUE TITLE
Wrong uses in examples

### ISSUE THREAD

**Issue by ToMe25** [srepollock/changelog-generator-action#4]
I tried using this changelog generator recently, and figured out both [this](https://github.com/marketplace/actions/simple-changelog-generator#example-usage) and [this](https://github.com/srepollock/changelog-generator-action#example-usage) example usage use `changelog-generator` as the repository name, instead of `changelog-generator-action`, causing the action to fail loading.

**Comment by srepollock** [comment]
Thanks for letting me know about the typo! I'll fix that now
