### ISSUE TITLE
[enhancement] Is it more convenient to update changelog in this action using PyGithub?

### ISSUE THREAD

**Issue by BobAnkh** [srepollock/changelog-generator-action#8]
I think it is more convinient to update changelog within the action by using PyGithub.

Are you interested in that feature? If so, I would be glad to contribute to this project.

**Comment by srepollock** [comment]
Is this in reference to the workflow file uploading changes to the PR branch?

Reference:
https://github.com/srepollock/changelog-generator-action/blob/b6de81fb7d8080560f1cc84ef7d1be2a88c53621/.github/workflows/master-pr-changelog.yaml#L8-L42

**Comment by BobAnkh** [comment]
Well, I mean to upload changes just by the script without using other actions, where  more inputs can be added to choose  uploading to PR branch or just pushing commits

I think it is more convenient to just use and configure one action to not only generating changelog and uploading it

**Comment by srepollock** [comment]
You mean removing this action all together and changing to using pygithub, or more along the lines of configuring pygithub in the workflow as opposed to committing to the PR branch?

**Comment by BobAnkh** [comment]
> You mean removing this action all together and changing to using pygithub, or more along the lines of configuring pygithub in the workflow as opposed to committing to the PR branch?

Yes, I mean to replace `actions/upload-artifact@v2` or `name: Add artifact to repo`  with new functions in changelog_generator.py, so that if I want to generate changelog and upload it,  I only need to configure this action. And we can set an option for choosing whether to submit PR or not.

**Comment by srepollock** [comment]
That would be fantastic! A great idea. Let me know if you want to work on it

**Comment by BobAnkh** [comment]
> That would be fantastic! A great idea. Let me know if you want to work on it

I will try to implement `feature/upload` first. 😄
